<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="soccf-tr5-001" name="component-tests(failed)" tests="2" failures="1" timestamp="7 Aug 2014 06:09:00 GMT" time="10.969" errors="0">
  <testcase name="testAll" time="2.809" classname="teammates.test.cases.logic.EvaluationsLogicTest"/>
  <testcase name="testAll" time="3.62" classname="teammates.test.cases.logic.FeedbackSessionsLogicTest">
    <failure type="com.google.apphosting.api.ApiProxy$CallNotFoundException" message="The API package &amp;apos;datastore_v3&amp;apos; or call &amp;apos;RunQuery()&amp;apos; was not found.">
      <![CDATA[com.google.apphosting.api.ApiProxy$CallNotFoundException: The API package 'datastore_v3' or call 'RunQuery()' was not found.
	at com.google.apphosting.api.ApiProxy$1.get(ApiProxy.java:170)
	at com.google.apphosting.api.ApiProxy$1.get(ApiProxy.java:168)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:86)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:86)
	at com.google.appengine.api.datastore.FutureHelper.getInternal(FutureHelper.java:71)
	at com.google.appengine.api.datastore.FutureHelper.quietGet(FutureHelper.java:32)
	at com.google.appengine.api.datastore.QueryResultsSourceImpl.peekQueryResultAndIfFirstRecordIndexList(QueryResultsSourceImpl.java:167)
	at com.google.appengine.api.datastore.QueryResultsSourceImpl.loadMoreEntities(QueryResultsSourceImpl.java:109)
	at com.google.appengine.api.datastore.QueryResultsSourceImpl.loadMoreEntities(QueryResultsSourceImpl.java:92)
	at com.google.appengine.api.datastore.QueryResultIteratorImpl.ensureLoaded(QueryResultIteratorImpl.java:145)
	at com.google.appengine.api.datastore.QueryResultIteratorImpl.hasNext(QueryResultIteratorImpl.java:64)
	at org.datanucleus.store.appengine.query.RuntimeExceptionWrappingIterator$1.get(RuntimeExceptionWrappingIterator.java:50)
	at org.datanucleus.store.appengine.query.RuntimeExceptionWrappingIterator$1.get(RuntimeExceptionWrappingIterator.java:46)
	at org.datanucleus.store.appengine.query.QueryExceptionWrappers$1.get(QueryExceptionWrappers.java:51)
	at org.datanucleus.store.appengine.query.QueryExceptionWrappers$2.get(QueryExceptionWrappers.java:86)
	at org.datanucleus.store.appengine.query.RuntimeExceptionWrappingIterator.hasNext(RuntimeExceptionWrappingIterator.java:105)
	at org.datanucleus.store.appengine.query.LazyResult.resolveAll(LazyResult.java:115)
	at org.datanucleus.store.appengine.query.LazyResult.size(LazyResult.java:110)
	at org.datanucleus.store.appengine.query.StreamingQueryResult.size(StreamingQueryResult.java:130)
	at org.datanucleus.store.query.AbstractQueryResult.isEmpty(AbstractQueryResult.java:312)
	at teammates.storage.api.FeedbackSessionsDb.getFeedbackSessionEntity(FeedbackSessionsDb.java:329)
	at teammates.storage.api.FeedbackSessionsDb.getFeedbackSession(FeedbackSessionsDb.java:114)
	at teammates.logic.core.FeedbackSessionsLogic.getFeedbackSession(FeedbackSessionsLogic.java:95)
	at teammates.logic.core.FeedbackSessionsLogic.isCreatorOfSession(FeedbackSessionsLogic.java:666)
	at teammates.logic.core.FeedbackQuestionsLogic.getFeedbackQuestionsForInstructor(FeedbackQuestionsLogic.java:199)
	at teammates.logic.core.FeedbackSessionsLogic.isFeedbackSessionCompletedByInstructor(FeedbackSessionsLogic.java:727)
	at teammates.test.cases.logic.FeedbackSessionsLogicTest.testSendReminderForFeedbackSession(FeedbackSessionsLogicTest.java:1739)
	at teammates.test.cases.logic.FeedbackSessionsLogicTest.testAll(FeedbackSessionsLogicTest.java:116)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testAll -->
</testsuite> <!-- component-tests(failed) -->
