<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="soccf-tr5-001" name="component-tests(failed)" tests="2" failures="1" timestamp="20 Aug 2014 12:31:29 GMT" time="55.268" errors="0">
  <testcase name="testSchedulingOfCreationOfSubmissions" time="3.449" classname="teammates.test.cases.logic.SubmissionTaskQueueLogicTest"/>
  <testcase name="testAdditionOfTaskToTaskQueue" time="41.676" classname="teammates.test.automated.FeedbackSessionPublishedReminderTest">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;3&amp;gt; but was:&amp;lt;2&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<3> but was:<2>
	at teammates.test.automated.FeedbackSessionPublishedReminderTest.testAdditionOfTaskToTaskQueue(FeedbackSessionPublishedReminderTest.java:137)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testAdditionOfTaskToTaskQueue -->
</testsuite> <!-- component-tests(failed) -->
